/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package feed2telegraph


fun main() {
    // Set the URL of the RSS feed
    // val feedUrl = "https://www.billboard-japan.com/d_news/doc.xml"

    // val feed = Feed(
    //     link  = feedUrl,
    //     title = "billboard-japan",
    //     lang  = "jpn",
    //     translated = false,
    // )

    val feed = Feed(
        link  = "https://rsshub.app/kbs/today/e",
        title = "kbs_eng",
        lang  = "eng",
        channelId = "-50",
        translated = false,
    )

    feed.parse()

    


}
