name: RSS to Telegram Bot

on:
  schedule:
    - cron: "*/30 * * * *" # 每30分钟运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  rss-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./small/feed_to_telegraph # 所有命令在small目录下执行

    steps:
    # 1. 检出代码（不包含data目录）
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 设置Python环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"



    # 4. 创建数据目录结构
    - name: Prepare data directory
      run: |
        mkdir -p ../../../data
        echo "数据目录准备就绪：$(realpath ../../../data)"

    # 5. 下载历史记录（静默失败）
    - name: Download history artifact
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: rss-history
        path: ../../../data

    # 6. 初始化空历史文件（如果不存在）
    - name: Initialize history file
      run: |
        if [ ! -f ../../../data/rss_updates.json ]; then
          echo '{}' > ../../../data/rss_updates.json
          echo "初始化空历史文件"
        else
          echo "使用现有历史文件"
        fi

    # 3. 安装uv（全局安装）
    - name: Install uv globally
      run: pip install --user uv

    # 4. 创建并激活虚拟环境
    - name: Create virtual environment
      run: |
        python -m uv venv .venv
        echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH

    # 4. 安装依赖
    - name: Sync dependencies
      run: |
        uv sync

# 6. 验证安装
    - name: Check installed packages
      run: |
        pip list
        python -c "import aiohttp; print(f'aiohttp version: {aiohttp.__version__}')"


# 8. 运行主程序
    - name: Run RSS Bot
      env:
        RSS_URL: ${{ secrets.RSS_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
      run: |
        python -m src.main

    # 9. 上传更新后的历史文件
    - name: Upload history artifact
      uses: actions/upload-artifact@v4
      with:
        name: rss-history
        path: ../../../data/rss_updates.json
        retention-days: 7
        overwrite: true
